### PR TITLE
Fixed the path

### PR DESCRIPTION
**Pull request by Daksh**
Associated Google Code In 2015 Task: https://codein.withgoogle.com/dashboard/task-instances/5666480997793792/?sp-page=1

### CODE REVIEW

**Comment by nemesiscodex** [comment]
Can you give a description of the problem and how you solved it, both in the pull request and the commit message. And as a title something more representative.

**Comment by Daksh** [comment]
"The activity was earlier trying to a directory that is not being used by the sugar core anymore
the current directory used by the core is used at https://github.com/sugarlabs/sugar/blob/master/src/jarabe/main.py#L359
Changed the directory the activity was earlier trying to use, and thus fix the activity, so that it works now!"
(Commit Message)

**Comment by Daksh** [comment]
As a part of solving the problem I had been looking at the icon theme given by the Gtk and the way one can change the set of icons by creating a theme rather than just changing the source. One way to solve this problem would have been to just create the icon in the sugar-artwork but then that is a very bad solution, so rather it is nice to keep the icon theme. On searching it was found that the directory which the activity referred to was not valid anymore, so I had to change it the way it was in Sugar core, given at https://github.com/sugarlabs/sugar/blob/master/src/jarabe/main.py#L359

**Comment by i5o** [comment]
Hello, it works, good job

**Pull request merged**
